- api/src/main/java/com/fnproject/fn/api/TypeWrapper.java
While reading the Javadoc I realized that it shows `&lt;` and `&gt;` inside of Javadoc sample for `TypeWrapper` which I generated and viewed as:
```bash
fdk-java/api$ mvn clean javadoc:javadoc
fdk-java/api$ firefox target/site/apidocs/com/fnproject/fn/api/TypeWrapper.html
```
The sample for revision 7ac184b0e37b65ef28d4609e78ba4d6d611b0fd4 does not represent compilable Java code:
```java
class GenericParent&lt;T&gt; {
public void someMethod(T t) { // do something with t }
}
class ConcreteClass extends GenericParent&lt;String&gt; { }
```
With my change the sample looks as it should:
```java
class GenericParent<T> {
public void someMethod(T t) { // do something with t }
}
class ConcreteClass extends GenericParent<String> { }
```
Please consider accepting my documentation fix.
> Use < and > inside of {@code} Javadoc section

- docs/FnFlowsUserGuide.md
Update FN container name from functions to fnserver at grabbing internal docker network IP
> Update FN container name

- examples/async-thumbnails/pom.xml
- examples/async-thumbnails/src/test/java/com/fnproject/fn/examples/ThumbnailsFunctionTest.java
- examples/regex-query/pom.xml
- fn-spring-cloud-function/pom.xml
- fn-spring-cloud-function/src/main/java/com/fnproject/springframework/function/SpringCloudFunctionInvoker.java
- fn-spring-cloud-function/src/main/java/com/fnproject/springframework/function/SpringCloudFunctionLoader.java
- fn-spring-cloud-function/src/main/java/com/fnproject/springframework/function/functions/SpringCloudConsumer.java
- fn-spring-cloud-function/src/main/java/com/fnproject/springframework/function/functions/SpringCloudFunction.java
- fn-spring-cloud-function/src/main/java/com/fnproject/springframework/function/functions/SpringCloudMethod.java
- fn-spring-cloud-function/src/main/java/com/fnproject/springframework/function/functions/SpringCloudSupplier.java
- fn-spring-cloud-function/src/test/java/com/fnproject/springframework/function/SimpleFunctionInspector.java
- fn-spring-cloud-function/src/test/java/com/fnproject/springframework/function/SpringCloudFunctionInvokerIntegrationTest.java
- fn-spring-cloud-function/src/test/java/com/fnproject/springframework/function/SpringCloudFunctionLoaderTest.java
- fn-spring-cloud-function/src/test/java/com/fnproject/springframework/function/testfns/EmptyFunctionConfig.java
- fn-spring-cloud-function/src/test/java/com/fnproject/springframework/function/testfns/FunctionConfig.java
- pom.xml
Updated dependency versions to reduce security problems
Using snyk.io tools we found several dependencies had security vulnerabilities
and could be updated. This does not remove all of them, but the remaining CVEs
are in transitive dependencies brought in by 3rd party code.
CVEs remain in:
async-thumbnails example (low priority to fix) through
- minio
- wiremock
fn-spring-cloud-function through
- spring-cloud-function-context
Additional changes were needed to adjust for API changes in updated dependencies:
async-thumbnails example:
- new minio client uses chunked file uploads so assertions needed changing
fn-spring-cloud-function:
- Several breaking API changes, and it seems now that Consumer behaviour is broken.
> Updated dependency versions to reduce security problems

- api/src/main/api/snapshot.sigfile
- api/src/main/java/com/fnproject/fn/api/FnFeatures.java
- runtime/src/main/java/com/fnproject/fn/runtime/EntryPoint.java
- testing-junit4/src/main/java/com/fnproject/fn/testing/FnTestingRule.java
Hey @tzezula  - i've made the FnFeature multi @repeatable and also dropped back to more pedestrian annotation methods - are these supported in substrate?
> make FnFeature multi-valued remove use of getAnnotationsByType

- examples/async-thumbnails/pom.xml
- examples/regex-query/pom.xml
- integration-tests/pom.xml
- pom.xml
Bumps Jackson version to 2.9.8 to address CVE-2018-19360, CVE-2018-19361 and CVE-2018-19362
> Bump Jackson version

- images/init-native/func.init.yaml
Note that an empty func.init.yaml should be present, if not CLI will complain that "init-image did not produce a valid func.init.yaml"
> Removed useless entries from the SVM func.yaml

- README.md
Removed user tutorial already included in tutorials. Reorganized and simplified. More work to do reviewing each of the docs linked from here.
> A first cut at updating and simplifying the Java FDK Readme. 

- .circleci/release.sh
By publishing tag to github first we ensure that no artifacts are pushed
for a version which isn't tagged.
Publishing to bintray last ensures that the CLI won't pick up a version
which is not pushed everywhere.
> Re-order release artifact publishing

- images/runtime/Dockerfile
Java 8 Dockerfile specified absolute path to `java` binary which has seemingly changed in latest versions of `openjdk:8-slim` image (possibly due to https://github.com/docker-library/openjdk/commit/3eb0351b208d739fac35345c85e3c6237c2114ec#diff-e29295585240d6f18a944f2a83a10505) and broke the build. This changes it to simply `java`.
> Fix path of java binary in Dockerfile

- README.md
Per Shaun, per Legal and for consistency, all FDKs should be titled Function Development Kit for <language>. Thus we are updating to **Function Development Kit for Java** where the title occurs.
> Update all names to Function Development Kit for Java

- flow-runtime/pom.xml
- pom.xml
- runtime/pom.xml
the FDK previously depended on httpmime rather than httpclient for historical reasons, this is not necessary and it can just depend on httpclient now.
> Remove HTTPMime dependency and just depend on AHC

- build.sh
- integration-tests/src/test/java/com/fnproject/fn/integrationtest/FunctionsTest.java
- runtime/pom.xml
- runtime/src/main/java-filtered/com/fnproject/fn/runtime/Version.java
- runtime/src/main/java/com/fnproject/fn/runtime/EntryPoint.java
- runtime/src/main/java/com/fnproject/fn/runtime/HTTPStreamCodec.java
- runtime/src/test/java/com/fnproject/fn/runtime/HTTPStreamCodecTest.java
This adds Fn-Fdk-Version to each response from the FDK - this allows services to track which version of the FDK is in use at a given time. 
In addition to the specific FDK version  java has several variants (java version, graal vs openJDK) 
Per discusion with @roroco  - I've added a comment to the version header  that encodes these 
This uses maven placeholders to rewrite the version number into a string literal - this is done to reduce startup time (by avoiding having to load resources at startup) and remove the need for substrate functions to explicitly include resources in their build configuration. 
the new header looks like this for graal: 
```
Fn-Fdk-Version: fdk-java/1.0.0-SNAPSHOT (jvm=Substrate VM, jvmv=1.8.0_222)
```
and for openjdk: 
```
Fn-Fdk-Version: fdk-java/1.0.0-SNAPSHOT …
```
> Add Fn-Fdk-Version to java fdk

- CONTRIBUTING.md
- examples/async-thumbnails/pom.xml
- examples/regex-query/pom.xml
- images/init-native/pom.xml
- integration-tests/funcs/flowAllFeatures/pom.xml
- integration-tests/pom.xml
- pom.xml
Version bumped multiple dependencies to more recent versions:
```
httpcore 4.4.10 -> 4.4.13
jackson-databind  2.10.3 -> 2.11.0
typetools 0.5.0 -> 0.6.2
httpclient 4.5.6 -> 4.5.12
mockito-core 2.21.0 -> 3.3.3
assertj-core 3.10.0 -> 3.16.1
```
Also added setup instructions for Mac users to `CONTRIBUTING.md`.
> Refresh the Java FDK dependencies to more recent versions.

- images/runtime/Dockerfile
- images/runtime/Dockerfile-jre11
This PR addresses issues with loading of resources into the classpath. Previously only the wildcards were used so only jar or JAR was loaded and all other resources like logging properties and other configuration yaml/json/.. files were omitted. By appending `/function/app` to classpath all resources in this directory will be loaded.
> Add resources to classpath

- integration-tests/funcs/flowAllFeatures/pom.xml
- runtime/src/main/java/com/fnproject/fn/runtime/EntryPoint.java
- runtime/src/main/java/com/fnproject/fn/runtime/MethodFunctionInvoker.java
- runtime/src/test/java/com/fnproject/fn/runtime/ConfigurationMethodsTest.java
- runtime/src/test/java/com/fnproject/fn/runtime/EndToEndInvokeTest.java
- runtime/src/test/java/com/fnproject/fn/runtime/ErrorMessagesTest.java
- runtime/src/test/java/com/fnproject/fn/runtime/FunctionConstructionTest.java
Logs are sometimes not emitted for failures that occur within function initialization - this means that errors related to: 
* Function construction 
* Incorrect handler methods 
* Non-existant classes
Are not logged 
It think this is caused by two things: 
* the  log framing tag is not emitted until after the method has been initalized, after these errors may have occured. 
*  The JVM is shut down before the logs are flushed to docker 
This change defers initialization of the function Runtime context until the first event is received, ensuring that initialization errors are logged, and also moves log framing out of the method invoker and up to the function entrypoint. 
This also keeps the JVM alive if there is an error in initalization.
> Logging is not always emitted when the function fails during startup

- experimental-native-image-support/src/main/java/com/fnproject/fn/nativeimagesupport/JacksonFeature.java
- experimental-native-image-support/src/test/java/com/fnproject/fn/nativeimagesupport/JacksonFeatureTest.java
- images/init-native/Dockerfile
This extends Jackson reflection matching to include adding reflective access for all classes that _have_ Jackson annotations as well as the classes they reference . 
This also changes the default Class Initializer behaviour default from "all at build time" to "all at runtime except for known-safe classes". This resolves an issue where a customer initializing config in static initializers were getting unexpected results as the fields were being initialized to null at compile time rather than getting their function config variables. 
Example output for an OCI client app: 
```
[func:26]    classlist:   4,363.04 ms,  1.19 GB
JacksonFeature: FnProject experimental Jackson feature loaded
JacksonFeature: Graal native image support is *experimental* it may not be stable and there may be cases …
```
> Extend Jackson feature to match and add reflection for classes

- runtime/pom.xml
This bundles the UDS socket JNI library within the runtime jar artifact 
This allows users building custom runtimes to fetch and extract this library on build  (without fetching the docker image) when building home-grown runtime images.
> Add Unix socket handling JNI library to runtime jar

- .circleci/config.yml
- .circleci/fix-java-for-surefire.sh
- .circleci/maven-settings.xml
- images/build/Dockerfile
- images/build/Dockerfile-jdk11
- images/build/cache-deps.sh
- images/build/local-settings.xml
- integration-tests/funcs/flowAllFeatures/Dockerfile
- integration-tests/funcs/flowBasic/Dockerfile
- integration-tests/funcs/flowBasicJDK8/Dockerfile
- integration-tests/funcs/flowExitHooks/Dockerfile
- integration-tests/funcs/flowTimeouts/Dockerfile
- integration-tests/funcs/helloFunc/Dockerfile
- integration-tests/funcs/httpgwfunc/Dockerfile
- integration-tests/funcs/httpgwfunc/func.yaml
- integration-tests/funcs/simpleFunc/Dockerfile
- integration-tests/funcs/simpleFunc/func.yaml
- integration-tests/src/main/java/com/fnproject/fn/integrationtest/IntegrationTestRule.java
- integration-tests/src/test/java/com/fnproject/fn/integrationtest/FlowTest.java
- integration-tests/src/test/java/com/fnproject/fn/integrationtest/FunctionsTest.java
Maven has added a default setting in the settings.xml which blocks access to any HTTP-based repository. However, as part of the FDK build we are running an HTTP server hosting the built JARs in a container and accessing it in a Maven command running in another container. This is not allowed anymore by default due to Maven's change.
We introduce a workaround that uses a local settings file to temporarily disable the blockage and redirects an HTTP-based repo queries to our local container running the HTTP server.
The change is only relevant for the copy-dependencies step of the build image creations, and the local settings file is deleted afterwards, in a way that does not even leave a layer with an "insecure" Maven settings file in the container.
Also we try to unbreak the CircleCI build …
> Workaround to make the build work after Maven fixed CVE-2021-26291

- api/src/main/api/snapshot.sigfile
- api/src/main/java/com/fnproject/fn/api/RuntimeContext.java
- api/src/main/java/com/fnproject/fn/api/tracing/TracingContext.java
- runtime/src/main/java/com/fnproject/fn/runtime/EntryPoint.java
- runtime/src/main/java/com/fnproject/fn/runtime/FunctionRuntimeContext.java
- runtime/src/main/java/com/fnproject/fn/runtime/coercion/ContextCoercion.java
- runtime/src/main/java/com/fnproject/fn/runtime/tracing/OCITracingContext.java
- runtime/src/test/java/com/fnproject/fn/runtime/tracing/OCITracingContextTest.java
**Overview**
Oracle Functions will soon release a feature providing an integration with the Oracle Application Performance Monitoring (APM) service. This service supports the sending of Zipkin formatted tracing data to a collector endpoint.
The service will provide the function code with data which includes:
- A boolean flag specifying whether the tracing integration is enabled for the function invocation
- A trace collector URL that can be used to configure Zipkin so that tracing data is sent there
- The "B3" formatted headers specifying the originating trace ID and span IDs (as specified by Zipkin)
This information is accessible by the function code in a Tracing Context provided by the FDK.
This change has no effect on existing functions, except that the keys "OCI_TRACING_ENABLED" and …
> Add support for Oracle Cloud Infrastructure tracing solution by providing a tracing context

- runtime/src/main/java/com/fnproject/fn/runtime/tracing/OCITracingContext.java
- runtime/src/test/java/com/fnproject/fn/runtime/tracing/OCITracingContextTest.java
Java-FDK provide the feature to enable tracing in the function declared. To ease it for user to have a facility to directly use a toggle button for enable and disable of this tracing feature we need to pass the mock value because the tracer(Zipkin) doesn't allow blank values and throws an exception which would be inconvenient for the end user. I have just added the mock values for the data to support the feature of enable and disable tracing by passing mock values.
> Change in Java FDK to support enable/disable feature of the apm integration tracing.

- pom.xml
Details available [here](https://nvd.nist.gov/vuln/detail/CVE-2022-42003).
> CVE-2022-42003: bump jackson version to 2.14.2
